### ISSUE TITLE
SQS job failing

### ISSUE THREAD

**Issue by vvval** [spiral/jobs#14]
Jobs on SQS are failing sometimes:
```
INFO[0158] job.PUSH jobs.checkEmailJob 0d1624d3-c8ff-4d26-a9e4-cb33feed4487
INFO[0159] job.RECV jobs.checkEmailJob 0d1624d3-c8ff-4d26-a9e4-cb33feed4487
INFO[0159] job.DONE jobs.checkEmailJob 0d1624d3-c8ff-4d26-a9e4-cb33feed4487 {707ms}

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x9cac2f]

goroutine 160 [running]:
github.com/spiral/jobs/broker/sqs.unpack(0xc000341100, 0x65746e6f630a3239, 0x3a657079742d746e, 0x746163696c707061, 0x77772d782f6e6f69, 0x752d6d726f662d77, 0x65646f636e656c72)
        C:/Users/.../go/src/github.com/spiral/jobs/broker/sqs/job.go:46 +0x10f
github.com/spiral/jobs/broker/sqs.(*queue).do(0xc000267490, 0xc00000c710, 0xc000183fa0, 0xc000341100, 0x3665316566353863, 0x3837666266626338)
        C:/Users/.../go/src/github.com/spiral/jobs/broker/sqs/queue.go:154 +0x40
github.com/spiral/jobs/broker/sqs.(*queue).serve.func1(0xc000267490, 0xc00000c710, 0xc000183fa0, 0xc000341100)
        C:/Users/.../go/src/github.com/spiral/jobs/broker/sqs/queue.go:116 +0x4d
created by github.com/spiral/jobs/broker/sqs.(*queue).serve
        C:/Users/.../go/src/github.com/spiral/jobs/broker/sqs/queue.go:115 +0xe4
```
.rr config:
```yaml
rpc:
  listen: "tcp://localhost:6002"

http:
  address: :8081
  workers.command: "php webroot/index.php rr"

jobs:
  sqs:
    key:      ...
    secret:   ...
    region:   us-east-2

  workers.command: "php webroot/index.php consumer"

  dispatch:
    jobs-*.pipeline: sqs

  pipelines:
    sqs:
      broker: sqs
      queue:  awsbounces
      declare:

  consume: ["sqs"]
```

**Comment by wolfy-j** [comment]
Did you use the same queue for jobs handler and for the native queue?

**Comment by wolfy-j** [comment]
More strict validation will be available in next update.
