### ISSUE TITLE
Terminating rr with SQS job failed with panic

### ISSUE THREAD

**Issue by vvval** [spiral/jobs#15]
I had a working rr with SQS jobs, pressing CTRL+C caused the next output:
```
^CDEBU[0462] [rpc]: stopped
DEBU[0462] [http]: stopped
INFO[0462] [sqs]: stopping {sqs}
ERRO[0462] [http]: http: Server closed
DEBU[0462] [ephemeral]: stopped
DEBU[0463] [sqs]: stopped {sqs}
DEBU[0463] [sqs]: stopped
DEBU[0463] [jobs]: stopped
panic: close of closed channel

goroutine 1 [running]:
github.com/spiral/jobs/broker/sqs.(*Broker).Stop(0xc000142680)
        C:/Users/.../go/src/github.com/spiral/jobs/broker/sqs/broker.go:99 +0x108
github.com/spiral/roadrunner/service.(*container).Stop(0xc000278420)
        C:/Users/.../go/src/github.com/spiral/roadrunner/service/container.go:205 +0xc2
github.com/spiral/jobs.(*Service).Stop(0xc000199ea0)
        C:/Users/.../go/src/github.com/spiral/jobs/service.go:141 +0x159
github.com/spiral/roadrunner/service.(*container).Stop(0xc00011b0e0)
        C:/Users/.../go/src/github.com/spiral/roadrunner/service/container.go:205 +0xc2
github.com/spiral/roadrunner/service.(*container).Serve(0xc00011b0e0, 0xb8e548, 0xc00026a6c0)
        C:/Users/.../go/src/github.com/spiral/roadrunner/service/container.go:193 +0x2b5
github.com/spiral/roadrunner/cmd/rr/cmd.serveHandler(0xc000134500, 0xc000142840, 0x0, 0x4)
        C:/Users/.../go/src/github.com/spiral/roadrunner/cmd/rr/cmd/serve.go:51 +0x74
github.com/spf13/cobra.(*Command).execute(0xc000134500, 0xc000142780, 0x4, 0x4, 0xc000134500, 0xc000142780)
        C:/Users/.../go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x10ec0c0, 0xc0001b1f20, 0x80b68a, 0xc00011b0f0)
        C:/Users/.../go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x10ec0c0, 0x5, 0xc0001426c0)
        C:/Users/.../go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/spiral/roadrunner/cmd/rr/cmd.Execute()
        C:/Users/.../go/src/github.com/spiral/roadrunner/cmd/rr/cmd/root.go:64 +0x31
main.main()
        D:/Projects/.../rr/main.go:39 +0x394
```

**Comment by wolfy-j** [comment]
Please check on latest build.
